name = "gloriafood-webhook-handler"
main = "main.py"
compatibility_date = "2024-05-10"

# ğŸ‘‡ AÃ‘ADE ESTA LÃNEA ğŸ‘‡
compatibility_flags = ["python_workers"]

[[secrets]]
binding = "SMARTPASSES_TOKEN"